-- H2 2.1.214;
;             
CREATE USER IF NOT EXISTS "SA" SALT '31e624dfbfde5fbf' HASH 'cc01e8602b5e96a1b3a528497e9bfdff7eea2cc11fb505d7cd9854f624f512e4' ADMIN;         
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1 RESTART WITH 9;    
CREATE MEMORY TABLE "PUBLIC"."BIDLIST"(
    "ID" INTEGER NOT NULL,
    "ACCOUNT" CHARACTER VARYING(255),
    "ASK" DOUBLE PRECISION,
    "ASK_QUANTITY" DOUBLE PRECISION,
    "BENCHMARK" CHARACTER VARYING(255),
    "BID" DOUBLE PRECISION,
    "BID_LIST_DATE" TIMESTAMP,
    "BID_QUANTITY" DOUBLE PRECISION NOT NULL,
    "BOOK" CHARACTER VARYING(255),
    "COMMENTARY" CHARACTER VARYING(255),
    "CREATION_DATE" TIMESTAMP,
    "CREATION_NAME" CHARACTER VARYING(255),
    "DEAL_NAME" CHARACTER VARYING(255),
    "DEAL_TYPE" CHARACTER VARYING(255),
    "REVISION_DATE" TIMESTAMP,
    "REVISION_NAME" CHARACTER VARYING(255),
    "SECURITY" CHARACTER VARYING(255),
    "SIDE" CHARACTER VARYING(255),
    "SOURCE_LIST_ID" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255),
    "TRADER" CHARACTER VARYING(255),
    "TYPE" CHARACTER VARYING(255)
);     
ALTER TABLE "PUBLIC"."BIDLIST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_23" PRIMARY KEY("ID");     
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.BIDLIST; 
INSERT INTO "PUBLIC"."BIDLIST" VALUES
(3, 'Account One', NULL, NULL, NULL, NULL, NULL, 12.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Type One');      
CREATE MEMORY TABLE "PUBLIC"."CURVE_POINT"(
    "ID" INTEGER NOT NULL,
    "AS_OF_DATE" TIMESTAMP,
    "CREATION_DATE" TIMESTAMP,
    "CURVE_ID" INTEGER NOT NULL,
    "CURVE_VALUE" DOUBLE PRECISION NOT NULL,
    "TERM" DOUBLE PRECISION NOT NULL
);
ALTER TABLE "PUBLIC"."CURVE_POINT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6084" PRIMARY KEY("ID");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CURVE_POINT;             
CREATE MEMORY TABLE "PUBLIC"."RATING"(
    "ID" INTEGER NOT NULL,
    "FITCH_RATING" CHARACTER VARYING(255),
    "MOODYS_RATING" CHARACTER VARYING(255),
    "ORDER_NUMBER" INTEGER NOT NULL,
    "SANDPRATING" CHARACTER VARYING(255)
);               
ALTER TABLE "PUBLIC"."RATING" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8F" PRIMARY KEY("ID");      
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.RATING;  
INSERT INTO "PUBLIC"."RATING" VALUES
(6, 'B', 'A', 5, 'A');  
CREATE MEMORY TABLE "PUBLIC"."RULENAME"(
    "ID" INTEGER NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "JSON" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "SQL_PART" CHARACTER VARYING(255),
    "SQL_STR" CHARACTER VARYING(255),
    "TEMPLATE" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."RULENAME" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");     
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.RULENAME;
INSERT INTO "PUBLIC"."RULENAME" VALUES
(8, 'Description 1', 'json 1', 'Name 1', 'sqlPart 1', 'sqlStr 1', 'Template 1');      
CREATE MEMORY TABLE "PUBLIC"."TRADE"(
    "ID" INTEGER NOT NULL,
    "ACCOUNT" CHARACTER VARYING(255),
    "BENCHMARK" CHARACTER VARYING(255),
    "BOOK" CHARACTER VARYING(255),
    "BUY_PRICE" DOUBLE PRECISION,
    "BUY_QUANTITY" DOUBLE PRECISION NOT NULL,
    "CREATION_DATE" TIMESTAMP,
    "CREATION_NAME" CHARACTER VARYING(255),
    "DEAL_NAME" CHARACTER VARYING(255),
    "DEAL_TYPE" CHARACTER VARYING(255),
    "REVISION_DATE" TIMESTAMP,
    "REVISION_NAME" CHARACTER VARYING(255),
    "SECURITY" CHARACTER VARYING(255),
    "SELL_PRICE" DOUBLE PRECISION,
    "SELL_QUANTITY" DOUBLE PRECISION,
    "SIDE" CHARACTER VARYING(255),
    "SOURCE_LIST_ID" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255),
    "TRADE_DATE" TIMESTAMP,
    "TRADER" CHARACTER VARYING(255),
    "TYPE" CHARACTER VARYING(255)
);      
ALTER TABLE "PUBLIC"."TRADE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4C5" PRIMARY KEY("ID");      
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.TRADE;   
INSERT INTO "PUBLIC"."TRADE" VALUES
(7, 'Account X', NULL, NULL, NULL, 35.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Type X');  
CREATE MEMORY TABLE "PUBLIC"."USER_ACCOUNT"(
    "ID" INTEGER NOT NULL,
    "FULLNAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "ROLE" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255)
);       
ALTER TABLE "PUBLIC"."USER_ACCOUNT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID"); 
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USER_ACCOUNT;            
INSERT INTO "PUBLIC"."USER_ACCOUNT" VALUES
(1, 'Administrator', '$2y$10$IBP5qFgrzcoHfKN2X6thmulbZ2jZDNi29PkVC2k4dG5Pl6nzsGFbC', 'ADMIN', 'admin'),
(2, 'User', '$2y$10$YmKdFBHtXRaTdwyAQvWLae4GIir5PPHQ.CMkwPnV.oOgyJkJVBGb6', 'USER', 'user');             
ALTER TABLE "PUBLIC"."CURVE_POINT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_608" CHECK("TERM" >= CAST(1.0 AS DOUBLE PRECISION)) NOCHECK;           
ALTER TABLE "PUBLIC"."BIDLIST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" CHECK("BID_QUANTITY" >= CAST(1.0 AS DOUBLE PRECISION)) NOCHECK;         
ALTER TABLE "PUBLIC"."TRADE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" CHECK("BUY_QUANTITY" >= CAST(1.0 AS DOUBLE PRECISION)) NOCHECK;           
ALTER TABLE "PUBLIC"."CURVE_POINT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" CHECK("CURVE_ID" >= 1) NOCHECK;     
ALTER TABLE "PUBLIC"."RATING" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" CHECK("ORDER_NUMBER" >= 1) NOCHECK;      
ALTER TABLE "PUBLIC"."CURVE_POINT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_60" CHECK("CURVE_VALUE" >= CAST(1.0 AS DOUBLE PRECISION)) NOCHECK;     
ALTER TABLE "PUBLIC"."TRADE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4C" CHECK("SELL_QUANTITY" >= CAST(1.0 AS DOUBLE PRECISION)) NOCHECK;         
